/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StudentLevel model module.
* @module model/StudentLevel
* @version 1.0.0
*/
export default class StudentLevel {
    /**
    * Constructs a new <code>StudentLevel</code>.
    * @alias module:model/StudentLevel
    * @class
    * @param type {String} 
    * @param level {Number} 
    */

    constructor(type, level) {
        

        
        

        this['type'] = type;this['level'] = level;

        
    }

    /**
    * Constructs a <code>StudentLevel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StudentLevel} obj Optional instance to populate.
    * @return {module:model/StudentLevel} The populated <code>StudentLevel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudentLevel();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {Number} level
    */
    level = undefined;








}


