/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleInventoryApi);
  }
}(this, function(expect, SimpleInventoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleInventoryApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be.a(SimpleInventoryApi.User);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property birthDate (base name: "birthDate")', function() {
      // uncomment below and update the code to test the property birthDate
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property profilePicture (base name: "profilePicture")', function() {
      // uncomment below and update the code to test the property profilePicture
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property bio (base name: "bio")', function() {
      // uncomment below and update the code to test the property bio
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property studentOf (base name: "studentOf")', function() {
      // uncomment below and update the code to test the property studentOf
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property experience (base name: "experience")', function() {
      // uncomment below and update the code to test the property experience
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

    it('should have the property skills (base name: "skills")', function() {
      // uncomment below and update the code to test the property skills
      //var instane = new SimpleInventoryApi.User();
      //expect(instance).to.be();
    });

  });

}));
